### ISSUE TITLE
有没有真实请求案例？

### ISSUE THREAD

**Issue by livelyPeng** [SilentFlute/umi3.x-ssr#1]
static async getInitialProps(ctx) {
    // console.log('ctx', ctx);

    const data = await wait(3000);

    return {
      data
    };
  }

你在这里面写个真实请求试试，各种问题就来了，跨域， 配置代理，然后会把你接口，变成页面路径访问

**Comment by SilentFlute** [comment]
没有用umijs的ssr方案, 这个库是提问时候建立的: https://github.com/umijs/umi/issues/4808, ssr方案我最后使用的是nextjs

**Comment by fikyair** [comment]
> 没有用umijs的ssr方案, 这个库是提问时候建立的: [umijs/umi#4808](https://github.com/umijs/umi/issues/4808), ssr方案我最后使用的是nextjs

对 已有项目切换 nextjs 是不成本有些大呢
